#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    automatic_update = true

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "checkers"

[[layers]]
  name = "git"

[[layers]]
  name = "github"

# lang layers

[[layers]]
  name = "lang#WebAssembly"

[[layers]]
  name = "lang#agda"

[[layers]]
  name = "lang#asciidoc"

[[layers]]
  name = "lang#c"

[[layers]]
  name = "lang#clojure"

[[layers]]
  name = "lang#csharp"
  highlight_types = 0

[[layers]]
  name = "lang#dart"

[[layers]]
  name = "lang#elixir"

[[layers]]
  name = "lang#elm"

[[layers]]
  name = "lang#erlang"

[[layers]]
  name = "lang#fsharp"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#graphql"

[[layers]]
  name = "lang#haskell"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#io"

[[layers]]
  name = "lang#java"

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#kotlin"

[[layers]]
  name = "lang#latex"

[[layers]]
  name = "lang#lisp"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#nix"

[[layers]]
  name = "lang#ocaml"

[[layers]]
  name = "lang#purescript"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#r"

[[layers]]
  name = "lang#ruby"

[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lang#scala"

[[layers]]
  name = "lang#scheme"

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#vim"

[[layers]]
  name = "lang#xml"

[[layers]]
  name = "lsp"


